
/* Drop Tables */

DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE LIKEY CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE BOARD
(
	ID number NOT NULL,
	USERNAME nvarchar2(20) NOT NULL,
	TITLE nvarchar2(50) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	HITCOUNT number NOT NULL,
	LIKEY number NOT NULL,
	FILES nvarchar2(100),
	POSTDATE timestamp DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE COMMENTS
(
	ID number NOT NULL,
	CONTENT nvarchar2(200) NOT NULL,
	POSTDATE timestamp DEFAULT SYSDATE,
	BOARD_ID number NOT NULL,
	USERNAME nvarchar2(20) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE LIKEY
(
	USERNAME nvarchar2(20) NOT NULL,
	BOARD_ID number NOT NULL,
	PRIMARY KEY (USERNAME, BOARD_ID)
);


CREATE TABLE MEMBERS
(
	USERNAME nvarchar2(20) NOT NULL,
	PASSWORD nvarchar2(20) NOT NULL,
	NAME nvarchar2(10) NOT NULL,
	REGIDATE date DEFAULT SYSDATE NOT NULL,
	ADDRESS nvarchar2(50),
	TELNUMBER varchar2(15),
	GENDER nvarchar2(5) NOT NULL,
	INTEREST nvarchar2(50) NOT NULL,
	EDU nvarchar2(10) NOT NULL,
	INTRO nvarchar2(2000) NOT NULL,
	PROFILE nvarchar2(50),
	PRIMARY KEY (USERNAME)
);



/* Create Foreign Keys */

ALTER TABLE COMMENTS
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES BOARD (ID)
;


ALTER TABLE LIKEY
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES BOARD (ID)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (USERNAME)
	REFERENCES MEMBERS (USERNAME)
;


ALTER TABLE COMMENTS
	ADD FOREIGN KEY (USERNAME)
	REFERENCES MEMBERS (USERNAME)
;


ALTER TABLE LIKEY
	ADD FOREIGN KEY (USERNAME)
	REFERENCES MEMBERS (USERNAME)
;



